services:
  deployer-backend:
    build:
      context: ./backend
    container_name: deployer-backend
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8081:8080"
    networks:
      - deployer-net

  deployer-frontend:
    build:
      context: ./frontend
    container_name: deployer-frontend
    ports:
      - "8082:80"
    networks:
      - deployer-net

networks:
  deployer-net:
    driver: bridge
