name: Build and Push Deployer Images

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      OWNER_LC: ${{ github.repository_owner }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Force lowercase owner
        run: echo "OWNER_LC=${OWNER_LC,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/sammcore-deployer-frontend:latest
            ghcr.io/${{ env.OWNER_LC }}/sammcore-deployer-frontend:${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/sammcore-deployer-backend:latest
            ghcr.io/${{ env.OWNER_LC }}/sammcore-deployer-backend:${{ github.sha }}
